version: '3.1'

services:

  db:
    image: postgres
    container_name: tm-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: time-manager-db
      POSTGRES_PASSWORD: 1234
    volumes:
      - tm-volume:/var/lib/postgresql/data

volumes:
  tm-volume: